spring.application.name=spring-boot-pet

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# Hikari CP
spring.datasource.hikari.maximum-pool-size=8

# Local overrides (DB credentials etc.).see application-local.properties
spring.config.import=optional:application-local.properties
